//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoDroid.DragAreaSample
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int green_dot = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int red_dot = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int translucent_dot = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int white_dot = 2130837508;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int dot_eight = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int dot_five = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int dot_four = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int dot_nine = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int dot_one = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int dot_seven = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int dot_six = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int dot_three = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int dot_two = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int dots = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int drag_area = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int report_view = 2131034123;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			private String()
			{
			}
		}
	}
}
